name: game-of-life-demo
channels:
  - intel
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy<1.24
  - numba-dpex
  - matplotlib
  - scipy
  - dpnp
  - dpctl
  - tbb=2021.4
  - opencv
setuptools~=65.6.3
numba~=0.56.3
numpy~=1.23.5
pytest~=7.1.2

dpnp~=0.11.2dev0
opencv-python~=4.7.0.72
