package:
  name: game-of-life-demo
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ./

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

test:
  requires:
    pytest
    pytest-cov

  imports:
    - game_of_life_demo

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numba
    - opencv

about:
  home: https://github.com/samaid/game-of-life-demo
  license: BSD-2
