package:
  name: game-of-life-demo
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  entry_points:
    - game_of_life = game_of_life_demo.game_of_life:main
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - WHEELS_OUTPUT_FOLDER

test:
  requires:
    - pytest =7.1.2
    - pytest-cov
    - pytest-mock =3.10.0
    - numpy ~=1.23
    - numba >=0.56.4
    - dpnp
    - dpctl
    - numba-dpex

  imports:
    - game_of_life_demo

requirements:
  build:
  host:
    - python
    - setuptools =65.6.3
    - git
    - wheel =0.38.4
    - numpy ~=1.23
    - numba >=0.56.4
    - opencv =4.6.0
    - dpnp
    - dpctl
    - numba-dpex

  run:
    - python
    - numpy ~=1.23
    - scipy ~= 1.7
    - numba >=0.56.4
    - opencv =4.6.0
    - dpnp
    - dpctl
    - numba-dpex

about:
  home: https://github.com/samaid/game-of-life-demo
  license: BSD-2
