package:
  name: game-of-life-demo
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - WHEELS_OUTPUT_FOLDER

test:
  requires:
    - pytest
    - pytest-cov

  imports:
    - game_of_life_demo

requirements:
  host:
    - python
    - setuptools
    - git
    - wheel
    - numba
    - opencv

  run:
    - python
    - numba
    - opencv

about:
  home: https://github.com/samaid/game-of-life-demo
  license: BSD-2
  
